type CSSProperties = Record<string, string | number>;

export const AppShellStyles: Record<string, CSSProperties> = {
  page: {
    minHeight: '100vh',
    background: 'linear-gradient(180deg, #F8FBF8 0%, #F7FAFC 28%, #F4F7FA 100%)',
  },
  header: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1.5fr) auto',
    gap: '32px',
    padding: '24px 32px 22px',
    borderBottom: '1px solid rgba(255, 255, 255, 0.12)',
    background: 'linear-gradient(180deg, #0F4C81 0%, #123F6B 100%)',
    alignItems: 'start',
    boxShadow: '0 10px 30px rgba(15, 76, 129, 0.18)',
  },
  brandColumn: {
    display: 'grid',
    gap: '8px',
  },
  eyebrow: {
    margin: 0,
    color: '#A9D7FF',
    textTransform: 'uppercase',
    fontWeight: 700,
    fontSize: '0.78rem',
    letterSpacing: '0.08em',
  },
  brand: {
    margin: 0,
    fontSize: 'clamp(2rem, 4vw, 3rem)',
    lineHeight: 1.02,
    color: '#FFFFFF',
  },
  subtitle: {
    margin: 0,
    color: '#F2C94C',
    maxWidth: '720px',
    fontSize: '1.05rem',
    fontWeight: 700,
  },
  mission: {
    margin: 0,
    color: 'rgba(255, 255, 255, 0.86)',
    maxWidth: '760px',
  },
  actions: {
    display: 'grid',
    gap: '14px',
    alignContent: 'start',
    justifyItems: 'end',
  },
  nav: {
    display: 'flex',
    gap: '10px',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
  },
  navLink: {
    padding: '10px 14px',
    borderRadius: '999px',
    background: 'transparent',
    minHeight: '44px',
    display: 'inline-flex',
    alignItems: 'center',
    color: 'rgba(255, 255, 255, 0.86)',
    border: '1px solid rgba(255, 255, 255, 0.14)',
    fontWeight: 600,
  },
  navLinkActive: {
    padding: '10px 14px',
    borderRadius: '999px',
    background: '#FFFFFF',
    minHeight: '44px',
    display: 'inline-flex',
    alignItems: 'center',
    color: '#0F4C81',
    border: '1px solid #FFFFFF',
    fontWeight: 700,
  },
  localeRow: {
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
  },
  localeButton: {
    minHeight: '40px',
    minWidth: '44px',
    borderRadius: '999px',
    border: '1px solid rgba(255, 255, 255, 0.16)',
    background: 'rgba(255, 255, 255, 0.08)',
    color: '#FFFFFF',
  },
  localeButtonActive: {
    minHeight: '40px',
    minWidth: '44px',
    borderRadius: '999px',
    border: '1px solid #F2C94C',
    background: '#F2C94C',
    color: '#12324A',
    fontWeight: 700,
  },
  breadcrumbWrapper: {
    padding: '14px 32px 0',
  },
  breadcrumbNav: {
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap',
    alignItems: 'center',
    color: '#5C6B7A',
    fontSize: '0.92rem',
  },
  breadcrumbLink: {
    color: '#0F4C81',
    textDecoration: 'none',
    fontWeight: 600,
  },
  breadcrumbCurrent: {
    color: '#16202A',
    fontWeight: 700,
  },
  breadcrumbSeparator: {
    color: '#8A99A8',
  },
  main: {
    padding: '20px 32px 32px',
  },
  footer: {
    marginTop: '32px',
    padding: '24px 32px 30px',
    borderTop: '1px solid rgba(255, 255, 255, 0.1)',
    background: 'linear-gradient(180deg, #123F6B 0%, #0F4C81 100%)',
    color: '#DCEBFA',
  },
  footerGrid: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1.4fr) minmax(0, 1fr)',
    gap: '20px',
    alignItems: 'start',
  },
  footerTitle: {
    margin: 0,
    color: '#FFFFFF',
    fontSize: '1rem',
  },
  footerText: {
    margin: '8px 0 0',
    color: 'rgba(255, 255, 255, 0.82)',
  },
  footerMeta: {
    display: 'grid',
    gap: '6px',
    justifyItems: 'end',
  },
  footerMetaText: {
    margin: 0,
    color: '#DCEBFA',
    textAlign: 'right',
  },
};
